// app/vue/src/App.tsx
(
  <RouterView />
  <datalist id="color-picker">
    <option value="#000000" title="black"></option>
    <option value="#FFFFFF" title="white"></option>
    <option value="#B0BEC5" title="gray"></option>
    <option value="#E03131" title="red"></option>
    <option value="#F08C00" title="orange"></option>
    <option value="#F7D77E" title="yellow"></option>
    <option value="#37B24D" title="green"></option>
    <option value="#15AABF" title="cyan"></option>
    <option value="#228BE6" title="blue"></option>
    <option value="#7048E8" title="purple"></option>
  </datalist>
)

// app/vue/src/App.vue
<template>
  <RouterView />
  <datalist id="color-picker">
    <option value="#000000" title="black"></option>
    <option value="#FFFFFF" title="white"></option>
    <option value="#B0BEC5" title="gray"></option>
    <option value="#E03131" title="red"></option>
    <option value="#F08C00" title="orange"></option>
    <option value="#F7D77E" title="yellow"></option>
    <option value="#37B24D" title="green"></option>
    <option value="#15AABF" title="cyan"></option>
    <option value="#228BE6" title="blue"></option>
    <option value="#7048E8" title="purple"></option>
  </datalist>
</template>
